### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by krt16s** [tasomaniac/OpenLinkWith#15]
Crashlytics and play-services are non-free software. Could you provide a gradle build flavor that works without them? Or maybe switch to a freeish alternative like ACRA?

**Comment by tasomaniac** [comment]
Ok, I will create a flavor with them removed. Are you going to assemble APK yourself and put that to F-Droid?

**Comment by krt16s** [comment]
When it's removed, I will try to build it on my local box and if it succeeds push the build recipe to fdroid. The build itself is done by f-droids buildserver, not by me.

**Comment by tasomaniac** [comment]
Fixed by https://github.com/tasomaniac/OpenLinkWith/commit/52e20624162808d3627c20a96ff1cad0aa56e8af

**Comment by tasomaniac** [comment]
@krt16s can you try to build it now? Thanks

**Comment by krt16s** [comment]
Done, might take some time to get build though.
