### ISSUE TITLE
Android Studio Import problem

### ISSUE THREAD

**Issue by gokselguren** [tasomaniac/OpenLinkWith#16]
Hi,
I checked out project successfully but when importing process of Android Studio starts, it shows error below;

> CreateProcess error=2, Sistem belirtilen dosyayý bulamýyor  Consult IDE log for more details (Help | Show Log)

**Comment by tasomaniac** [comment]
Is that the only output? It should include more details I think. 

Can you try to run `./gradlew build` if that is successful, I believe the problem is with your IDE.

**Comment by gokselguren** [comment]
Yes, "show log" opens log directory. Log file may include more details about error. I will try importing again and inspect log file for detail.

There is a link http://stackoverflow.com/questions/19874546/createprocess-error-2-the-system-cannot-find-the-file-specified-android-studio about this problem. Also, I will try this solution. Thanks.
