### ISSUE TITLE
Perhaps grab more intents from Intent Intercept?

### ISSUE THREAD

**Issue by TPS** [tasomaniac/OpenLinkWith#17]
This project reminds me of a less-technical version of II, so it be worth borrowing from said more-mature app. https://github.com/intrications/intent-intercept/blob/master/app/src/main/AndroidManifest.xml should get you started on what all you may expand. ☺

**Comment by tasomaniac** [comment]
Thank you for the feedback. Open Link With is not designed to intercept all links. I intentionally do that because I want users to keep their default app as they are. Open LInk With is not everywhere, it is just available when you share a text with it.

**Comment by tasomaniac** [comment]
I looked at the intents in intent-interceptor over and over again but I don't think Open Link With needs to intercept any of it. 

If you want, you can give me use cases and I can implement them. Thank you.
