### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [tasomaniac/OpenLinkWith#19]
It would be nice if you can publish this app on F-Droid too.

**Comment by tasomaniac** [comment]
It would be nice if you could check before opening the issue. :) 

Here it is available. 
https://f-droid.org/repository/browse/?fdid=com.tasomaniac.openwith.floss

**Comment by rugk** [comment]
Ough, have not seen that. Sorry...

**Comment by rugk** [comment]
But it is outdated. It is still version "1.0.7-floss - Added on 2016-01-23"...

**Comment by tasomaniac** [comment]
No problem. Do you know how do we update the app in f-droid. Thanks.

**Comment by rugk** [comment]
I think it is possible to let it automatically update when a new release is published on GitHub.
Look at [the wiki page](https://f-droid.org/wiki/page/com.tasomaniac.openwith.floss):
> We have the current version of this app. (Check mode: None) (Auto-update mode: None)
> The current (recommended) version is 1.0.7-floss (version code 10700). 

So there is currently no auto-update used. See https://f-droid.org/wiki/page/Inclusion_How-To#Updating and https://f-droid.org/manual/fdroid.html#Update-Check-Mode for more information how FDroid can update the apps.
I'd suggest you to contact the FDroid maintainer of your app (see the Wiki page and their merge requests) or just go ahead and create a merge request by yourself.
