### ISSUE TITLE
Default Browser support

### ISSUE THREAD

**Issue by tasomaniac** [tasomaniac/OpenLinkWith#26]
Related to the app blocking issue #21 

In most use cases blocking need of an app is usually for browsers. There are non-uninstallable browser apps on phones that user may not want to use. And we should offer them for every possible link shared with OLW. 

Instead of blocking support, other idea would be to have default browser support. 

In this context, another option would be to say "not offer browsers at all" which which will cause OLW to never open browsers but always use native apps.

**Comment by TPS** [comment]
Just FYI, a similar RFE's in https://github.com/tasomaniac/beta-checker/issues/1.
