### ISSUE TITLE
floss f-droid version didn't update to 2.1

### ISSUE THREAD

**Issue by TacoTheDank** [tasomaniac/OpenLinkWith#40]
im pretty sure something's wrong with either the setup of the app somewhere, or it's something on f-droid's side.

go over to their gitlab and create an issue, since they'll probably need your input anyway

either way i think youll have to push a new version

**Comment by tasomaniac** [comment]
Hi, thanks for the report. I need to manually upgrade f-droid every time I
publish an update. Since I have dynamically computed version code and name
they don't support auto update. Not sure if there is a solution.

Thanks.

**Comment by TacoTheDank** [comment]
well here's your problem xd

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.tasomaniac.openwith.floss.txt
```
Auto Update Mode:None
Update Check Mode:None
```

**Comment by tasomaniac** [comment]
The auto update modes available at f-droid are not compatible it seems. If
you know how to change it to an appropriate value, I would appreciate it.

**Comment by TacoTheDank** [comment]
I guess just not have the version codes dynamically generated ¯\\\_(ツ)_/¯

**Comment by tasomaniac** [comment]
Update request for 2.3 is live. Closing this for now. 

https://gitlab.com/fdroid/fdroiddata/merge_requests/3726
