### ISSUE TITLE
"Always use" option does not appear on LineageOS with microG and Firefox

### ISSUE THREAD

**Issue by kenogo** [tasomaniac/OpenLinkWith#53]
So, when I open for example a wikipedia link in firefox, I do get the option to share it with this app, but it just immediately opens the wikipedia app. I don't get the option to always launch it in the app automatically.

So basically, it behaves exactly the same as the button that is already included in Firefox natively. As it says in the title, I use LineageOS (version 15.1, based on Android 8.1.0) and microG (version 0.2.6) instead of official google services. It might be related to that, I'll have to read up on how Android works in that regard and take a look in the source code later.

**Comment by tasomaniac** [comment]
Hi, there is only one native app detected, OLW would not give you the "Always use" option since it is not necessary. This is relevant when you have multiple apps for Wikipedia links.

I hope that answers to your question. If not, screenshots would be awesome to describe it.

**Comment by kenogo** [comment]
@tasomaniac Well but how do I make links automatically open in Wikipedia instead of in a browser tab, then?

**Comment by kenogo** [comment]
@tasomaniac Oh it seems I completely misunderstood the purpose of this app, then. Thanks for clarifying!

**Comment by tasomaniac** [comment]
Thanks.

Did you see the advanced section in settings to enable OLW as a browser? With that you can have a faster cycle to intercept links. Although I heard feedback that it does not work with Firefox. It may be because Firefox keeps link clicks to itself.

**Comment by kenogo** [comment]
@tasomaniac Yeah I've seen that but I can confirm that it doesn't seem to change anything in Firefox. It's a shame really, probably gonna switch to Chromium then.
