### ISSUE TITLE
Google Photo 

### ISSUE THREAD

**Issue by Mongoose69** [tasomaniac/OpenLinkWith#55]
Is it possible for it to open Google Photo app when you're in the web app?

**Comment by tasomaniac** [comment]
Hi, Thanks for the report. 

I just looked into what Google Photos support as links. They only support public links. Shared albums etc. Even though you are signed-in inside both Browser and Google Photos they don't open private pictures via links. 

If you find a link with 'share' in it, that should work. Can you try that for me?

Thanks.

**Comment by Mongoose69** [comment]
Once I shared it, it was OK.
Thanks anyway
