### ISSUE TITLE
Translate addresses to open links in "unsupported" apps

### ISSUE THREAD

**Issue by quaqo** [tasomaniac/OpenLinkWith#59]
Certain apps, like Twitter Lite, only register to handle a subset of domains (i.e. mobile.twitter.com), it would be very usefull if OLW could have a sort of "translate address" feature like the one sported by  [this app](https://play.google.com/store/apps/details?id=com.maubis.linkswitch) I stumbled upon.

In the Twitter Lite case just adding "mobile." to "twitter.com/*." renders the Lite app able to handle normal twitter links.

The same goes for reddit apps that can't correctly handle "Open in App" (official app) reddit links when opened within a browser.

This feature would open up a lot of possibilities.

EDIT: it would basically mean to let the user customize the "UrlFixer" module.

**Comment by tasomaniac** [comment]
Thanks for the feedback. This app looks really similar to what Open Link With does.

As you mentioned, UrlFixer already does this. I'm just unsure about the UI where I would allow users to customize this. It's really tricky. 

And honestly, they don't change that often. I have bunch of fixes for different apps and I extend them as long as I have feedback from users. 

Do you have any example where mobile links do not work for you?
