### ISSUE TITLE
Add apps to suggestions list

### ISSUE THREAD

**Issue by beckbg** [tasomaniac/OpenLinkWith#63]
Might be quite the edge case and more a feature request than an issue but I'd love to be able to manually select an app from ALL apps instead of just those suggested

...I'm trying to get an authentication url to open in the Lexia Core5 reading app on a technically unsupported device. The Lexia website gets upset at the device/browser, so I'd like to try opening directly in the Lexia app -- on a supported device, the URL goes through some processing and redirects to open the app, so I'm not sure this will even work. The Lexia app won't show up in Open Link With... though, just the local browsers, so I can't even try. Could be something with Lexia, or something with my device (an Amazon Fire HD 10, *cringe* I've already had to modify it to get Lexia on there at all.)

**Comment by tasomaniac** [comment]
Thanks for the suggestion. I thought about this extensively. In my research, I realized that this will also not work in majority of the times. I'm pretty sure that even if OLW send you to the Lexia app, it will either redirect you back or give an error. In a lot of cases, the apps also just crash if they receive anything unexpected.

**Comment by beckbg** [comment]
Fair enough, thanks for the swift reply! Thanks, too, for your previous research and thoughtfulness and for your considerable ongoing work with this free project. It's a fantastic tool.

**Comment by tasomaniac** [comment]
Thanks. That means a lot to me. 😊
