### ISSUE TITLE
Remove tracking parameters from links

### ISSUE THREAD

**Issue by laurentlbm** [tasomaniac/OpenLinkWith#65]
As a user, I would like to set _Open Link With_ as my browser and have it both un-shorten the link and remove all tracking query string parameters (e.g. utm_*, ref, fbclid) before opening it.

I'm not sure this fits in the scope of this app, but since you already un-shorten links, I thought might as well suggest it. 

Essentially, it would do what these app do, but without the extra step of another share: 
- https://play.google.com/store/apps/details?id=com.catchingnow.share
- https://play.google.com/store/apps/details?id=com.chilyashev.sharelinkcleaner

**Comment by tasomaniac** [comment]
Thanks a lot for taking time to create this. I agree that this is kind of not related to the original goal of the project. But it is also easy to integrate since I have all necessary mechanism there. Will do this under advanced section in settings.
