### ISSUE TITLE
App settings screen is shown in the background when opened in browser mode

### ISSUE THREAD

**Issue by Atemu** [tasomaniac/OpenLinkWith#83]
When the app is open in the background at the time a link is opened (browser mode), the settings screen is shown in the background like this

![Screenshot_20220526-050307_Open Link With](https://user-images.githubusercontent.com/18599032/170407239-09c94e28-8f6b-46c7-989d-20188accf724.png)

The app the link was shared from should be shown in the background instead; just like it works in sharing mode.

This issue does *not* occur when the settings screen isn't open in the background (i.e. app was closed via app drawer).

PS: Thank you *so* much for making Android 12 bearable.

**Comment by tasomaniac** [comment]
Very weird. I have Pixel 6 with Android 12 and I don't see this issue. Which device do you use? I wonder if this is device specific?

**Comment by Atemu** [comment]
Cheeseburger with lineageos 19.1, though it's a month out of date.

Note that this only happens if the app's settings screen is currently open in recent apps. When I swipe the app out of recent apps, it works just as expected.

So for repro:

1. Open the app's settings
2. Switch to another app
3. Open link in other app

**Comment by tasomaniac** [comment]
So, these exact steps do not reproduce the issue for me. It must be a bug in lineage

**Comment by 1fexd** [comment]
I can reproduce the issue on Stock Android 13 on a Pixel 5. The crucial factor here is that the app has to be open in the recents menu.

**Comment by 1fexd** [comment]
I have addressed this issue in PR #98 @tasomaniac
