### ISSUE TITLE
Feature: Hide app icon from app list

### ISSUE THREAD

**Issue by askmrsinh** [tasomaniac/OpenLinkWith#93]
Thank you for maintaining this.

How do you feel about adding a toggle to hide the app icon from app list? Since this is more of an utility app and one would not need to open it again after the initial setup.

**Comment by tasomaniac** [comment]
Hi, thanks for reaching out.

Hiding from launcher makes sense if the app settings screen is accessible from somewhere else like a wigdet etc.

A lot of launchers support this functionality out of the box. Please use those to achieve this.
