### ISSUE TITLE
Does not work with Android 13

### ISSUE THREAD

**Issue by herrmann0319** [tasomaniac/OpenLinkWith#96]
Please fix. I am dying for this functionality.

Thanks,

Steven

**Comment by tasomaniac** [comment]
Hi, it should actually work fine with Android 13. Can you describe your issue?

**Comment by herrmann0319** [comment]
I figured it out. I am trying to use it for Youtube links to open in YouTube Revanced Extended bc they are currently opening in the browserr. When I click Always it opens in the app but doesn't save that app in preferred apps list. I just tried it with a different app and it worked. The problem seems to be with Yt Revanced and now that I'm thinking about it I think it started opening in the browser after I installed it in the first place. I'm going to delete it and use my regular youtube app again which i am a premium subsriber of anyway, problem solved. Thanks for getting back to me so quickly I really appreciate it.
